
fun main() {
    throw dynamicException("My", "Hallo exception!")
}


